sudo: required
services:
  - docker

before_install:
  - docker build -t guomingyuan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true guomingyuan/react-test npm test -- --coverage

after_success:
  - docker build -t guomingyuan/multi-client ./client
  - docker build -t guomingyuan/multi-nginx ./nginx
  - docker build -t guomingyuan/multi-server ./server
  - docker build -t guomingyuan/multi-worker ./worker
  # Login to Dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push all images to dockerhub
  - docker push guomingyuan/multi-client
  - docker push guomingyuan/multi-nginx
  - docker push guomingyuan/multi-server
  - docker push guomingyuan/multi-worker

language: generic
